apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: grpc-web-chat-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /chat.Chat
            backend:
              serviceName: grpc-web-chat-backend
              servicePort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: grpc-web-chat-backend
spec:
  clusterIP: None
  selector:
    app: grpc-web-chat-backend
  ports:
    - name: grpc-web-chat-backend
      port: 8080
      targetPort: 8080
      protocol: TCP

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: grpc-web-chat-backend
  labels:
    app: grpc-web-chat-backend
spec:
  selector:
    matchLabels:
      app: grpc-web-chat-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: grpc-web-chat-backend
    spec:
      containers:
        - name: proxy
          image: grpc-web-chat_proxy:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
            - name: envoy-admin
              containerPort: 9901
        - name: backend
          image: grpc-web-chat_backend:latest
          imagePullPolicy: Never
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 50051
