apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: grpc-web-chat-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /chat.Chat
            backend:
              serviceName: proxy
              servicePort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  selector:
    app: proxy
  ports:
    - name: proxy
      port: 8080
      targetPort: 8080
      protocol: TCP

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: grpc-web-chat_proxy:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
            - name: envoy-admin
              containerPort: 9901
