apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: "chat"
spec:
  clusterIP: None
  selector:
    app: backend
  ports:
    - name: backend
      port: 50051
      targetPort: 50051
      protocol: TCP

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backend
  namespace: "chat"
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 698712139551.dkr.ecr.ap-northeast-1.amazonaws.com/grpc-web-chat_backend:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
