apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: "chat"
spec:
  selector:
    app: proxy
  type: LoadBalancer
  ports:
    - name: proxy
      port: 8080
      targetPort: 8080
      protocol: TCP

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: proxy
  namespace: "chat"
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: 698712139551.dkr.ecr.ap-northeast-1.amazonaws.com/grpc-web-chat_proxy:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: envoy-admin
              containerPort: 9901
